export const REPORTSCASINO_GAMEID_LOAD = "REPORTSCASINO_GAMEID_LOAD";
export const REPORTSCASINO_GAMEID_GETDATA = "REPORTSCASINO_GAMEID_GETDATA";
export const REPORTSCASINO_GAMEID_FILTER = "REPORTSCASINO_GAMEID_FILTER";
